application:
  subdomain: aiclient2api
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://aiclient2api:3000/
  ingress:
    - protocol: tcp
      port: 8085
      service: aiclient2api
      description: "Gemini OAuth callback"
    - protocol: tcp
      port: 8086
      service: aiclient2api
      description: "Antigravity OAuth callback"
    - protocol: tcp
      port: 1455
      service: aiclient2api
      description: "Codex OAuth callback"
    - protocol: tcp
      port: 19876
      service: aiclient2api
      description: "Kiro OAuth callback (instance 1)"
    - protocol: tcp
      port: 19877
      service: aiclient2api
      description: "Kiro OAuth callback (instance 2)"
    - protocol: tcp
      port: 19878
      service: aiclient2api
      description: "Kiro OAuth callback (instance 3)"
    - protocol: tcp
      port: 19879
      service: aiclient2api
      description: "Kiro OAuth callback (instance 4)"
    - protocol: tcp
      port: 19880
      service: aiclient2api
      description: "Kiro OAuth callback (instance 5)"
services:
  aiclient2api:
    # justlikemaki/aiclient-2-api:2.11.5.2
    # upstream: justlikemaki/aiclient-2-api:3.3.6
    image: registry.lazycat.cloud/czyt/justlikemaki/aiclient-2-api:889b59bfc85e3b29
    binds:
      - /lzcapp/var/configs:/app/configs
